language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

git:
  depth: 1

services:
  - mysql

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.2
    - php: nightly

before_install:
  - composer self-update
  - cp app/config/parameters.yml.travis app/config/parameters.yml

install:
  - composer install

before_script:
  - php --version
  - php bin/console --version
  - vendor/bin/phpunit --version

script:
  - vendor/bin/phpcs -s --config-set ignore_warnings_on_exit 1
  - vendor/bin/php-cs-fixer fix --diff --dry-run
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
