app:
    resource: '@AppBundle/Controller/'
    type: annotation

# LightSAML routes
lightsaml_sp:
    resource: "@LightSamlSpBundle/Resources/config/routing.yml"
    prefix: saml

logout:
    path: /logout
